### PR TITLE
Enable software installation in Runner's AUT

### PR DESCRIPTION
**Pull request by kristanm1**
Added new runner argument '-enableSoftwareInstallation' to enable Software Installation in launch configuration

### CODE REVIEW

**Comment by kristanm1** [comment]
Another solution could be argument like '-launchConfiguration pathToLaunchConfiguration' from where runner could read launch configuration and set attributes to current launch configuration which are read. This argument would minimize the need of multiple runner arguments which define launch configuration

**Comment by kristanm1** [comment]
@basilevs please review

**Comment by basilevs** [comment]
RCPTT should be able to restore original state of AUT to perform next test. Usually state management is done via contexts, but this MR has none. How is installed or update software removed or downgraded?

**Comment by basilevs** [comment]
> Another solution could be argument like '-launchConfiguration pathToLaunchConfiguration' from where runner could read launch configuration and set attributes to current launch configuration which are read. This argument would minimize the need of multiple runner arguments which define launch configuration

Runner has no launch configurations.

**Comment by kristanm1** [comment]
> > Another solution could be argument like '-launchConfiguration pathToLaunchConfiguration' from where runner could read launch configuration and set attributes to current launch configuration which are read. This argument would minimize the need of multiple runner arguments which define launch configuration
> 
> Runner has no launch configurations.

I mean to pass runner AUTs launch configuration.

Imagine creating AUT in RCPTT ide and after everything is setup just copy created launch configuration from WORKSPACE_LOC/.metadata/.plugins/.metadata/.plugins/org.eclipse.debug.core/.launches and pass it to runner with argument.

**Comment by kristanm1** [comment]
> RCPTT should be able to restore original state of AUT to perform next test. Usually state management is done via contexts, but this MR has none. How is installed or updated software removed or downgraded?
> 
> ATM, additional software can be injected into AUT with [Injection options](https://eclipse.dev/rcptt/documentation/userguide/runner/arguments/#injection-options)

Reason why I need this argument is because I want to test some eclipse based programs which won't start as AUT without 'Support software installation in the launched application' enabled.

Without 'Software Installation' enabled I get error:
`!ENTRY org.eclipse.osgi 4 0 2024-01-19 09:29:15.128
!MESSAGE Application error
!STACK 1
java.lang.IllegalStateException: Unable to acquire application service. Ensure that the org.eclipse.core.runtime bundle is resolved and started (see config.ini).
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:81)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)`

**Comment by kristanm1** [comment]
In folder where eclipse in installed I changed configuration/org.eclipse.equinox.simpleconfigurator/bundles.info so bundles have absolute locations but the problem persists..

Can you direct me how can I solve this issue? @basilevs

**Comment by basilevs** [comment]
> Imagine creating AUT in RCPTT ide and after everything is setup just copy created launch configuration from WORKSPACE_LOC/.metadata/.plugins/org.eclipse.debug.core/.launches and pass it to runner with argument.

This would not work, because launch configuration relies on workspace and active target platform to prepare the launch (resolve necessary bundles). Neither are available in runner.

**Comment by kristanm1** [comment]
> Runner allows to [customize VM and application arguments](https://eclipse.dev/rcptt/documentation/userguide/runner/arguments/#basic-command-line-options) passed to AUT. There is no need for a dedicated flag.

How can I set attribute IPDELauncherConstants.GENERATE_PROFILE to true with VM and application arguments?

**Comment by basilevs** [comment]
@kristanm1 does the corresponding checkbox RCPTT IDE produce desirable results for this usecase?

**Comment by kristanm1** [comment]
> @kristanm1 does the corresponding checkbox RCPTT IDE produce desirable results for this usecase?

Yes, it works in RCPTT IDE and if proposed runner argument is added it works with runner too.

**Comment by basilevs** [comment]
@kristanm1 please add the corresponding flag in maven plugin and document both in 
https://github.com/eclipse/rcptt-website/blob/sculpin/source/documentation/userguide/runner/arguments.md (note the branch)

**Comment by kristanm1** [comment]
> @kristanm1 please add the corresponding flag in [maven plugin](https://github.com/eclipse/org.eclipse.rcptt/blob/master/maven-plugin/rcptt-maven-plugin/src/main/java/org/eclipse/rcptt/maven/ExecuteMojo.java) and document both in https://github.com/eclipse/rcptt-website/blob/sculpin/source/documentation/userguide/runner/arguments.md (note the branch)

added maven plugin argument and create pull request: [https://github.com/eclipse/rcptt-website/pull/1](https://github.com/eclipse/rcptt-website/pull/1)
please review @basilevs

**Comment by kristanm1** [comment]
@basilevs  I noticed that maven plugin argument which I added needs to have explicitly defined value to true, and presence of <enableSoftwareInstallation> is not enough.. 

I am working on this issue

**Comment by basilevs** [comment]
> @basilevs I noticed that maven plugin argument which I added needs to have explicitly defined value to true, and presence of <enableSoftwareInstallation> is not enough..
> 
> I am working on this issue

This sounds like a normal Maven behavior, do not worry about it.

**Comment by kristanm1** [comment]
> > @basilevs I noticed that maven plugin argument which I added needs to have explicitly defined value to true, and presence of  is not enough..
> > I am working on this issue
> 
> This sounds like a normal Maven behavior, user has to supply the value as configuration element body, do not worry about it. Just make sure that if XML element is absent, the resulting configuration does not add the argument to Runner's command line.

Yes, if XML element is absent no argument is added to Runners arguments

**Comment by kristanm1** [comment]
@basilevs I believe added argument works as expected and added documentation to [https://github.com/eclipse/rcptt-website/tree/sculpin](https://github.com/eclipse/rcptt-website/tree/sculpin).

Do I need to do anything else before pull request will be merged?

**Comment by basilevs** [comment]
Thanks, I will review this. Probably on a weekend.

**Pull request merged**
